name: "Bug report"
description: Report a bug found while using gomobile-ipfs.
labels: ["bug", "🔍 Ready for Review"]
assignees:
- jefft0
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the bug you
        encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of gomobile-ipfs are you using?
      placeholder: v1.7.0
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: Language version and compiler version
      description: What programming language version and compiler are you using?
      placeholder: go1.17.13, javac 11.0.12, Android Studio 2021.2.1 for Android 12
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Provide a bug description and a code snippet if applicable.
      placeholder: |
       1. Set up this environment ...
       2. Add this code ...
       3. Call this function ...
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: >-
        Output after code execution including stack traces, debug logs, etc.
      placeholder: Currently ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Please provide what would be your expectation to happen.
      placeholder: In this situation, gomobile-ipfs should ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What is your development environment?
      placeholder: macOS 10.15.7 on Samsung Galaxy S20
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      placeholder: Any other details?
